### ISSUE TITLE
hi,when i run  main.py,there was  a error.Do you know why?

### ISSUE THREAD

**Issue by 2212168851** [chenyuntc/PyTorchText#7]
Traceback (most recent call last):
  File "main.py", line 159, in <module>
    fire.Fire()  
  File "/usr/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 102, in main
    for ii,((title,content),label) in tqdm.tqdm(enumerate(dataloader)):
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 242, in __init__
    self._put_indices()
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 290, in _put_indices
    indices = next(self.sample_iter, None)
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/TH/generic/THTensorMath.c:2247

**Comment by 2212168851** [comment]
i do not change any of programs

**Comment by chenyuntc** [comment]
It seems that something was wrong with your data preprocessing.

**Comment by chandnikathuria1992** [comment]
hi
i am getting same error in my project on UCF dataset.
Have u got any solution to this?
